all:	checkpoint2.1.bin

checkpoint2.1.bin:	checkpoint2.1.kc
	${HOME}/OSStudentMaterial/kickc/bin/kickc.sh -a $<

test2.1:	checkpoint2.1.bin
	xmega65 -kickup checkpoint2.1.bin

checkpoint2.2.bin:	checkpoint2.2.kc
	${HOME}/OSStudentMaterial/kickc/bin/kickc.sh -a $<

test2.2:	checkpoint2.2.bin
	xmega65 -kickup checkpoint2.2.bin

checkpoint2.3.bin:	checkpoint2.3.kc
	${HOME}/OSStudentMaterial/kickc/bin/kickc.sh -a $<

test2.3:	checkpoint2.3.bin
	xmega65 -kickup checkpoint2.3.bin

checkpoint2.4.bin:	checkpoint2.4.kc
	${HOME}/OSStudentMaterial/kickc/bin/kickc.sh -a $<

test2.4:	checkpoint2.4.bin
	xmega65 -kickup checkpoint2.4.bin

checkpoint2.5.bin:	checkpoint2.5.kc
	${HOME}/OSStudentMaterial/kickc/bin/kickc.sh -a $<

test2.5:	checkpoint2.5.bin
	xmega65 -kickup checkpoint2.5.bin